In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("kidney_disease.csv")

In [3]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

#now we can see our dataset it's a classification dataset before 
#creating model using Machine learning classification we have to clean the dataset.

In [4]:
dataset.isna().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

#so we have lots of null values we can't process this file, because ML model not work with this nan values, 
#so we have to clean it

#Let's understand the snario of missing values in the dataset. The above details 
#for whole column values so split it by numerical and categorical

In [5]:
#now check for outliers to find whether mean is good or median is good for this dataset?

In [6]:
from Univariate import Univariate #Import class from .py file 
#From file name import class name

In [7]:
#from class name.function name()
quan,qual=Univariate.quan_qual(dataset)

In [8]:
quan

['id', 'age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo']

In [9]:
qual

['rbc',
 'pc',
 'pcc',
 'ba',
 'pcv',
 'wc',
 'rc',
 'htn',
 'dm',
 'cad',
 'appet',
 'pe',
 'ane',
 'classification']

In [10]:
from Univariate import Univariate 
import pandas as pd

In [11]:
import pandas as pd
descriptive_As= Univariate.descriptive_Tab(dataset,quan)

In [12]:
descriptive_As

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo
Mean,199.5,51.4834,76.4691,1.01741,1.01695,0.450142,148.037,57.4257,3.07245,137.529,4.62724,12.5264
Median,199.5,55,80,1.02,0,0,121,42,1.3,138,4.4,12.65
Mode,0,60,80,1.02,0,0,99,46,1.2,135,3.5,15
Q1:25%,99.75,42,70,1.01,0,0,99,27,0.9,135,3.8,10.3
Q2:50%,199.5,55,80,1.02,0,0,121,42,1.3,138,4.4,12.65
Q3:75%,299.25,64.5,80,1.02,2,0,163,66,2.8,142,4.9,15
99%,395.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q4:100%,399,90,180,1.025,5,5,490,391,76,163,47,17.8
IQR,199.5,22.5,10,0.01,2,0,64,39,1.9,7,1.1,4.7
1.5rule,299.25,33.75,15,0.015,3,0,96,58.5,2.85,10.5,1.65,7.05
lesser_per,-199.5,8.25,55,0.995,-3,0,3,-31.5,-1.95,124.5,2.15,3.25
greater_per,598.5,98.25,95,1.035,5,0,259,124.5,5.65,152.5,6.55,22.05
Mini,0,2,50,1.005,0,0,22,1.5,0.4,4.5,2.5,3.1
Max,399,90,180,1.025,5,5,490,391,76,163,47,17.8

In [13]:
lesser_de,greater_de=Univariate.detect_lesser_greater(quan,descriptive_As)

In [15]:
lesser_de

['age', 'bp', 'sod', 'hemo']

In [16]:
greater_de

['bp', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot']

In [18]:
#so in this dataset we have lots of outliers 
#we have to replace it for our dataset validation.
outliers_free=Univariate.Replace_outliers(dataset,lesser_de,greater_de,descriptive_As)

D:\Week-5_Datascience_Univariate\Assignment_Data_preprocessing_chronical kidney desease\Univariate.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[column_names][dataset[column_names]<descriptive[column_names]["lesser_per"]]=descriptive[column_names]
D:\Week-5_Datascience_Univariate\Assignment_Data_preprocessing_chronical kidney desease\Univariate.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[column_names][dataset[column_names]>descriptive[column_names]["greater_per"]]=descriptive[column_names]

In [19]:
outliers_free

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo
Mean,199.5,51.4834,76.4691,1.01741,1.01695,0.450142,148.037,57.4257,3.07245,137.529,4.62724,12.5264
Median,199.5,55,80,1.02,0,0,121,42,1.3,138,4.4,12.65
Mode,0,60,80,1.02,0,0,99,46,1.2,135,3.5,15
Q1:25%,99.75,42,70,1.01,0,0,99,27,0.9,135,3.8,10.3
Q2:50%,199.5,55,80,1.02,0,0,121,42,1.3,138,4.4,12.65
Q3:75%,299.25,64.5,80,1.02,2,0,163,66,2.8,142,4.9,15
99%,395.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q4:100%,399,90,180,1.025,5,5,490,391,76,163,47,17.8
IQR,199.5,22.5,10,0.01,2,0,64,39,1.9,7,1.1,4.7
1.5rule,299.25,33.75,15,0.015,3,0,96,58.5,2.85,10.5,1.65,7.05
lesser_per,-199.5,8.25,55,0.995,-3,0,3,-31.5,-1.95,124.5,2.15,3.25
greater_per,598.5,98.25,95,1.035,5,0,259,124.5,5.65,152.5,6.55,22.05
Mini,0,2,50,1.005,0,0,22,1.5,0.4,4.5,2.5,3.1
Max,399,90,180,1.025,5,5,490,391,76,163,47,17.8

In [21]:
import numpy as np #(Create imputer model for all quan columns)
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan,strategy='median')#since we have lots of outliers we use median to replace the nan values.
sim_imp=imp.fit_transform(dataset[quan])

In [22]:
sim_imp

array([[  0. ,  48. ,  80. , ..., 139. ,   4.4,  15.4],
       [  1. ,  55. ,  70. , ..., 139. ,   4.4,  11.3],
       [  2. ,  62. ,  80. , ..., 139. ,   4.4,   9.6],
       ...,
       [397. ,  12. ,  80. , ..., 137. ,   4.4,  15.8],
       [398. ,  17. ,  60. , ..., 135. ,   4.9,  14.2],
       [399. ,  58. ,  80. , ..., 141. ,   3.5,  15.8]])

In [23]:
#now convert it as a dataframe using pandas 
df=pd.DataFrame(sim_imp,columns=quan)

In [24]:
df

        id   age    bp     sg   al   su    bgr    bu   sc    sod  pot  hemo
0      0.0  48.0  80.0  1.020  1.0  0.0  121.0  36.0  1.2  139.0  4.4  15.4
1      1.0  55.0  70.0  1.020  4.0  0.0  117.0  18.0  0.8  139.0  4.4  11.3
2      2.0  62.0  80.0  1.010  2.0  0.0  117.0  53.0  1.8  139.0  4.4   9.6
3      3.0  48.0  70.0  1.005  4.0  0.0  117.0  56.0  3.8  139.0  2.5  11.2
4      4.0  51.0  80.0  1.010  2.0  0.0  106.0  26.0  1.4  139.0  4.4  11.6
..     ...   ...   ...    ...  ...  ...    ...   ...  ...    ...  ...   ...
395  395.0  55.0  80.0  1.020  0.0  0.0  140.0  49.0  0.5  150.0  4.9  15.7
396  396.0  42.0  70.0  1.025  0.0  0.0   75.0  31.0  1.2  141.0  3.5  16.5
397  397.0  12.0  80.0  1.020  0.0  0.0  100.0  26.0  0.6  137.0  4.4  15.8
398  398.0  17.0  60.0  1.025  0.0  0.0  114.0  50.0  1.0  135.0  4.9  14.2
399  399.0  58.0  80.0  1.025  0.0  0.0  131.0  18.0  1.1  141.0  3.5  15.8

[400 rows x 12 columns]

In [25]:
df.isna().sum()

id      0
age     0
bp      0
sg      0
al      0
su      0
bgr     0
bu      0
sc      0
sod     0
pot     0
hemo    0
dtype: int64

In [26]:
#next clean qual columns by using mode.
import numpy as np #(Create imputer model for all quan columns)
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
si_imp=imp.fit_transform(dataset[qual])

In [27]:
df1=pd.DataFrame(si_imp, columns= qual)

In [28]:
df1

,rbc,pc,pcc,ba,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,normal,normal,notpresent,notpresent,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,normal,normal,notpresent,notpresent,38,6000,5.2,no,no,no,good,no,no,ckd
2,normal,normal,notpresent,notpresent,31,7500,5.2,no,yes,no,poor,no,yes,ckd
3,normal,abnormal,present,notpresent,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,normal,normal,notpresent,notpresent,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,normal,normal,notpresent,notpresent,47,6700,4.9,no,no,no,good,no,no,notckd
396,normal,normal,notpresent,notpresent,54,7800,6.2,no,no,no,good,no,no,notckd
397,normal,normal,notpresent,notpresent,49,6600,5.4,no,no,no,good,no,no,notckd
398,normal,normal,notpresent,notpresent,51,7200,5.9,no,no,no,good,no,no,notckd
399,normal,normal,notpresent,notpresent,53,6800,6.1,no,no,no,good,no,no,notckd

In [29]:
#Now check it 
df1.isna().sum()

rbc               0
pc                0
pcc               0
ba                0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [30]:
df.isna().sum()

id      0
age     0
bp      0
sg      0
al      0
su      0
bgr     0
bu      0
sc      0
sod     0
pot     0
hemo    0
dtype: int64

In [32]:
result = pd.concat([df1, df], axis=1)

In [33]:
result

,rbc,pc,pcc,ba,pcv,wc,rc,htn,dm,cad,...,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo
0,normal,normal,notpresent,notpresent,44,7800,5.2,yes,yes,no,...,80.0,1.020,1.0,0.0,121.0,36.0,1.2,139.0,4.4,15.4
1,normal,normal,notpresent,notpresent,38,6000,5.2,no,no,no,...,70.0,1.020,4.0,0.0,117.0,18.0,0.8,139.0,4.4,11.3
2,normal,normal,notpresent,notpresent,31,7500,5.2,no,yes,no,...,80.0,1.010,2.0,0.0,117.0,53.0,1.8,139.0,4.4,9.6
3,normal,abnormal,present,notpresent,32,6700,3.9,yes,no,no,...,70.0,1.005,4.0,0.0,117.0,56.0,3.8,139.0,2.5,11.2
4,normal,normal,notpresent,notpresent,35,7300,4.6,no,no,no,...,80.0,1.010,2.0,0.0,106.0,26.0,1.4,139.0,4.4,11.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,normal,normal,notpresent,notpresent,47,6700,4.9,no,no,no,...,80.0,1.020,0.0,0.0,140.0,49.0,0.5,150.0,4.9,15.7
396,normal,normal,notpresent,notpresent,54,7800,6.2,no,no,no,...,70.0,1.025,0.0,0.0,75.0,31.0,1.2,141.0,3.5,16.5
397,normal,normal,notpresent,notpresent,49,6600,5.4,no,no,no,...,80.0,1.020,0.0,0.0,100.0,26.0,0.6,137.0,4.4,15.8
398,normal,normal,notpresent,notpresent,51,7200,5.9,no,no,no,...,60.0,1.025,0.0,0.0,114.0,50.0,1.0,135.0,4.9,14.2
399,normal,normal,notpresent,notpresent,53,6800,6.1,no,no,no,...,80.0,1.025,0.0,0.0,131.0,18.0,1.1,141.0,3.5,15.8

In [34]:
#I think order is matter 
Clean_dataset = pd.concat([df, df1], axis=1)

In [35]:
Clean_dataset

,id,age,bp,sg,al,su,bgr,bu,sc,sod,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0.0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,139.0,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1.0,55.0,70.0,1.020,4.0,0.0,117.0,18.0,0.8,139.0,...,38,6000,5.2,no,no,no,good,no,no,ckd
2,2.0,62.0,80.0,1.010,2.0,0.0,117.0,53.0,1.8,139.0,...,31,7500,5.2,no,yes,no,poor,no,yes,ckd
3,3.0,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,139.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4.0,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,139.0,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395.0,55.0,80.0,1.020,0.0,0.0,140.0,49.0,0.5,150.0,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396.0,42.0,70.0,1.025,0.0,0.0,75.0,31.0,1.2,141.0,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397.0,12.0,80.0,1.020,0.0,0.0,100.0,26.0,0.6,137.0,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398.0,17.0,60.0,1.025,0.0,0.0,114.0,50.0,1.0,135.0,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399.0,58.0,80.0,1.025,0.0,0.0,131.0,18.0,1.1,141.0,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [36]:
Clean_dataset.isna().sum()

id                0
age               0
bp                0
sg                0
al                0
su                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
rbc               0
pc                0
pcc               0
ba                0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [37]:
#thankyou mam for your support.
#our dataset now free from nan and outliers we can pass it in any models.